all:
  hosts:
    ${name}:
      ansible_host: ${ipaddress}
  vars:
    ansible_user: ${userctn}
    ansible_python_interpreter: /usr/local/bin/python3.11
    ansible_ssh_private_key_file: ${privkeyctn}
