---
- name: install hls
  hosts: all
  become: true

  vars:

  environment:
    http_proxy: "${proxy}"
    https_proxy: "${proxy}"
    no_proxy: "${noproxy}"

  roles:
    - roles/bastille
    # - roles/bsd-nginx
