---
# handlers file for roles/postgres
- name: reload_postgres
  service:
    name: postgresql
    state: reloaded
    enabled: yes

- name: restart_postgres
  service:
    name: postgresql
    state: restarted
    enabled: yes
